apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: quarkus-build-native
spec:
  workspaces:
    - name: source
  steps:
    - name: maven-package
      image: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java17
      workingDir: /workspace/source
      resources:
        requests:
          memory: "2Gi"
        limits:
          memory: "4Gi"
      script: |
        #!/bin/bash
        set -e
        sh ./mvnw package -Dquarkus.native.native-image-xmx=2G -Dnative