apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: hello-quarkus-test-build
  labels:
    sandbox: hello-quarkus
    learn-pipelines: pipeline 
spec: 
  workspaces: 
    - name: shared-workspace
    - name: maven-settings
  params: 
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/alam23/DeployOpenshiftTest.git
  - name: IMAGE
    type: string
    description: image to be built from the code
    default: image-registry.openshift-image-registry.svc:5000/andersonandyalberto2-dev/hello-quarkus:latest
  tasks: 
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: maven-package-native
    taskRef:
      name: maven
      kind: ClusterTask
    params:
      - name: MAVEN_IMAGE
        value: 'registry.access.redhat.com/ubi8/ubi-minimal:8.10'
      - name: GOALS
        value:
          - '-B'
          - '-ntp'
          - package
          - '-Dnative'
    workspaces:
      - name: source
        workspace: shared-workspace
      - name: maven-settings
        workspace: maven-settings
    runAfter:
      - fetch-repository
  - name: build-image 
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
    - maven-package-native
  - name: apply-manifests 
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter: 
    - build-image