apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: quarkus-build-event-listener
  labels:
    app: quarkus-hello
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: hello-quarkus-trigger