apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: quarkus-build-event-listener
  labels:
    app: quarkus-hello
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: quarkus-pipeline-binding
      name: quarkus-build-trigger
      template:
        ref: quarkus-build-trigger-template