apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: quarkus-build-trigger-template
  labels:
    app: quarkus-hello
spec:
  params:
    - name: git-repository-url
      default: "https://github.com/alam23/DeployOpenshiftTest.git"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: hello-quarkus-test-build-
      spec:
        pipelineRef:
          name: hello-quarkus-test-build
        params:
          - name: git-repository-url
            value: $(tt.params.git-repository-url)
        workspaces:
          - name: maven-settings
            persistentVolumeClaim:
              claimName: maven-pvc
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: source-pvc